Bluetooth: Audio: Bugfix - call bass.c DEVICE_INIT with unique name
bass.c called DEVICE_INIT with the same first parameter (dev_name) as
tbs.c did.

After the rebase, this caused the build to break, due to
gen_handles.py asserting:

File
"[...]/zephyr/scripts/gen_handles.py", line 194, in main
assert len(devices) == len(handles), 'mismatch devices and handles'
AssertionError: mismatch devices and handles
ninja: build stopped: subcommand failed.

Signed-off-by: Asbjørn Sæbø <asbjorn.sabo@nordicsemi.no>